from setuptools import setup, find_packages

setup(
    name="v1_depth_map",
    version="v2.0",
    packages=find_packages(),
    url="https://github.com/znamlab/v1_depth_map",
    license="MIT",
    author="Antonin Blot, Yiran He, Petr Znamenskiy",
    author_email="yiran.he@crick.ac.uk",
    description="Analysis for V1 depth map project",
    install_requires=[
        "numpy",
        "pandas",
        "pathlib",
        "seaborn",
        "matplotlib",
        "scipy",
        "tables",
        "scikit-learn",
        "tqdm",
        "scikit-image",
        "defopt",
        "roifile",
        "plotly",
        "kaleido",
        "jupyter",
        "notebook",
        "ipykernel",
        "black",
        "wayla @ git+ssh://git@github.com/znamlab/wayla.git@dev",
        "flexiznam @ git+ssh://git@github.com/znamlab/flexiznam.git@v0.4",
        "znamutils @ git+ssh://git@github.com/znamlab/znamutils.git@v0.9",
        "cottage_analysis @ git+ssh://git@github.com/znamlab/cottage_analysis.git@v2.0",
    ],
)
